# Generated by Django 4.2.11 on 2025-01-13 20:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('code', models.CharField(max_length=15, verbose_name='code')),
                ('price_market_triggers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=125), size=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_classification', models.CharField(choices=[('BUL', 'Bullish'), ('BER', 'Bearish'), ('CON', 'Consolidating'), ('RET', 'Retracement')], max_length=3, verbose_name='general classification')),
                ('market_structure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, null=True, size=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='code')),
                ('daily_objective', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True), blank=True, null=True, size=1)),
                ('weekly_objective', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True), blank=True, null=True, size=1)),
                ('monthly_objective', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True), blank=True, null=True, size=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_trade', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), size=10)),
                ('active_trade', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), size=10)),
                ('post_trade', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), size=10)),
                ('guidelines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), size=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='code')),
                ('trading_style', models.CharField(choices=[('STT', 'Short term'), ('MTT', 'Medium term'), ('LTT', 'Long term'), ('SWI', 'Swing trading'), ('SCP', 'Scalping'), ('DYT', 'Day trading')], max_length=3, verbose_name='trading_style')),
                ('markets', models.CharField(choices=[('COM', 'Commodities'), ('FUT', 'Futures'), ('DRV', 'Derivatives'), ('FOX', 'Forex')], max_length=3, verbose_name='markets')),
                ('trading_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Day-Off'), blank=True, null=True, size=5)),
                ('adages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), blank=True, null=True, size=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('routines', models.ManyToManyField(blank=True, related_name='trading_plans', related_query_name='trading_plan', to='tasks.routine')),
                ('target_profile', models.ManyToManyField(blank=True, related_name='trading_plans', related_query_name='trading_plan', to='trading_plan.objectiveprofile')),
                ('trade_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_plans', related_query_name='trading_plan', to='trading_plan.trademanagement')),
            ],
        ),
        migrations.CreateModel(
            name='TradingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preffered_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday')], max_length=3), size=5)),
                ('preffered_session', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LON', 'London'), ('ASI', 'Asia'), ('NYC', 'New York')], max_length=3), size=5)),
                ('preffered_hour', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HR1', '01:00'), ('HR2', '02:00'), ('HR3', '03:00'), ('HR4', '04:00'), ('HR5', '05:00')], max_length=3), size=24)),
                ('positive_price_market_signatures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=25)),
                ('negative_price_market_signatures', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=25)),
                ('risk_appetite', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], max_length=3, verbose_name='risk appetite')),
                ('riskreward_profile', models.CharField(choices=[('OTT', '1:2'), ('OTR', '1:3'), ('OTF', '1:4')], max_length=3, verbose_name='reward profile')),
                ('avg_duration', models.DurationField(verbose_name='average duration')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('market_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_models', related_query_name='trading_model', to='trading_plan.marketconditions')),
                ('trading_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_models', related_query_name='trading_model', to='trading_plan.tradingplan')),
            ],
        ),
    ]
