# Generated by Django 4.2.11 on 2025-01-18 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('trading_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='code')),
                ('adages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=125, null=True), blank=True, null=True, size=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_profile', models.ManyToManyField(blank=True, related_name='trading_plans', related_query_name='trading_plan', to='trading_plan.objectiveprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='tradingplan',
            name='routines',
        ),
        migrations.RemoveField(
            model_name='tradingplan',
            name='target_profile',
        ),
        migrations.RemoveField(
            model_name='tradingplan',
            name='trade_management',
        ),
        migrations.RemoveField(
            model_name='tradingmodel',
            name='trading_plan',
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='routines',
            field=models.ManyToManyField(blank=True, related_name='trading_models', related_query_name='trading_model', to='tasks.routine'),
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='trading_style',
            field=models.CharField(choices=[('STT', 'Short term'), ('MTT', 'Medium term'), ('LTT', 'Long term'), ('SWI', 'Swing trading'), ('SCP', 'Scalping'), ('DYT', 'Day trading')], default='DYT', max_length=3, verbose_name='trading_style'),
        ),
        migrations.DeleteModel(
            name='TradeManagement',
        ),
        migrations.DeleteModel(
            name='TradingPlan',
        ),
    ]
