# Generated by Django 4.2.11 on 2025-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_plan', '0002_journal_remove_tradingplan_routines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingmodel',
            name='preffered_hour',
        ),
        migrations.RemoveField(
            model_name='tradingmodel',
            name='preffered_session',
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='preffered_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='preffered_sessions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='price_market_triggers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='adages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketconditions',
            name='market_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingmodel',
            name='negative_price_market_signatures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingmodel',
            name='positive_price_market_signatures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingmodel',
            name='preffered_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
