# Generated by Django 4.2.11 on 2025-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_plan', '0003_remove_tradingmodel_preffered_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingmodel',
            name='code',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='title',
            field=models.CharField(default='', max_length=125, verbose_name='title'),
            preserve_default=False,
        ),
    ]
