# Generated by Django 4.2.11 on 2025-01-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_plan', '0002_journal_remove_tradingplan_routines_and_more'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', related_query_name='trade', to='trading_plan.journal'),
        ),
    ]
