# Generated by Django 4.2.11 on 2025-01-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='rules_observed',
        ),
    ]
